"""add_channel_integration_support

Revision ID: 95e2e592fcaa
Revises: a7a1ebba7aa8
Create Date: 2026-03-05 06:58:59.735893

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e2e592fcaa'
down_revision: Union[str, Sequence[str], None] = 'a7a1ebba7aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configurations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'WEB_FORM', 'API', name='channel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('response_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_response_length', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configurations_channel'), 'channel_configurations', ['channel'], unique=True)
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('webhook_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PROCESSING', 'COMPLETED', 'FAILED', name='webhookprocessingstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_processing_status'), 'webhook_delivery_logs', ['processing_status'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_received_at'), 'webhook_delivery_logs', ['received_at'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_webhook_type'), 'webhook_delivery_logs', ['webhook_type'], unique=False)
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', 'WEB_FORM', 'API', name='channel'), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_entries_customer_id'), 'rate_limit_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_entries_window_start'), 'rate_limit_entries', ['window_start'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.add_column('messages', sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('messages', sa.Column('parent_message_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('webhook_signature', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_messages_parent_message_id'), 'messages', ['parent_message_id'], unique=False)
    op.create_index(op.f('ix_messages_retry_after'), 'messages', ['retry_after'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_retry_after'), table_name='messages')
    op.drop_index(op.f('ix_messages_parent_message_id'), table_name='messages')
    op.drop_column('messages', 'webhook_signature')
    op.drop_column('messages', 'retry_after')
    op.drop_column('messages', 'retry_count')
    op.drop_column('messages', 'parent_message_id')
    op.drop_column('messages', 'thread_id')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_rate_limit_entries_window_start'), table_name='rate_limit_entries')
    op.drop_index(op.f('ix_rate_limit_entries_customer_id'), table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    op.drop_index(op.f('ix_webhook_delivery_logs_webhook_type'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_received_at'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_processing_status'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_index(op.f('ix_channel_configurations_channel'), table_name='channel_configurations')
    op.drop_table('channel_configurations')
    # ### end Alembic commands ###
