"""Refactor agent metrics and add observability

Revision ID: a7a1ebba7aa8
Revises: 459bcf301ab0
Create Date: 2026-02-28 07:34:00.387990

Major changes:
- Refactor agent_metrics table from generic metrics to agent execution tracking
- Add observability fields: conversation_id, tokens_used, latency_ms, tool_call_count, estimated_cost, success, error_message
- Convert all timestamps to timezone-aware (DateTime(timezone=True))
- Rename meta_data to metadata in customers, conversations, knowledge_base tables
- Remove unique constraint on customer_identifiers (identifier_type, identifier_value)
- Drop HNSW vector index on knowledge_base.embedding

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a1ebba7aa8'
down_revision: Union[str, Sequence[str], None] = '459bcf301ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_metrics', sa.Column('conversation_id', sa.Uuid(), nullable=False))
    op.add_column('agent_metrics', sa.Column('tokens_used', sa.Integer(), nullable=False))
    op.add_column('agent_metrics', sa.Column('latency_ms', sa.Integer(), nullable=False))
    op.add_column('agent_metrics', sa.Column('tool_call_count', sa.Integer(), nullable=False))
    op.add_column('agent_metrics', sa.Column('estimated_cost', sa.Float(), nullable=False))
    op.add_column('agent_metrics', sa.Column('success', sa.Boolean(), nullable=False))
    op.add_column('agent_metrics', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('agent_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('agent_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_agent_metrics_conversation_id'), 'agent_metrics', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'agent_metrics', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('agent_metrics', 'dimensions')
    op.drop_column('agent_metrics', 'metric_value')
    op.drop_column('agent_metrics', 'recorded_at')
    op.drop_column('agent_metrics', 'metric_name')
    op.alter_column('channel_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('channel_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('conversations', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('conversations', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('conversations', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('conversations', 'meta_data')
    op.alter_column('customer_identifiers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customer_identifiers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_identifier_type_value'), 'customer_identifiers', type_='unique')
    op.add_column('customers', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('customers', 'meta_data')
    op.add_column('knowledge_base', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('knowledge_base', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('knowledge_base_embedding_idx'), table_name='knowledge_base', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tickets', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tickets', 'resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('knowledge_base_embedding_idx'), 'knowledge_base', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('knowledge_base', 'metadata')
    op.add_column('customers', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('customers', 'metadata')
    op.create_unique_constraint(op.f('uq_identifier_type_value'), 'customer_identifiers', ['identifier_type', 'identifier_value'], postgresql_nulls_not_distinct=False)
    op.alter_column('customer_identifiers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_identifiers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('conversations', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.alter_column('conversations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('conversations', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conversations', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('conversations', 'metadata')
    op.alter_column('channel_configs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('channel_configs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('agent_metrics', sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('agent_metrics', sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('agent_metrics', sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('agent_metrics', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_agent_metrics_conversation_id'), table_name='agent_metrics')
    op.alter_column('agent_metrics', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_metrics', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('agent_metrics', 'error_message')
    op.drop_column('agent_metrics', 'success')
    op.drop_column('agent_metrics', 'estimated_cost')
    op.drop_column('agent_metrics', 'tool_call_count')
    op.drop_column('agent_metrics', 'latency_ms')
    op.drop_column('agent_metrics', 'tokens_used')
    op.drop_column('agent_metrics', 'conversation_id')
    # ### end Alembic commands ###
